language: cpp
compiler:
  - clang
  - gcc
before_install:
  - sudo apt-add-repository ppa:sonkun/sfml-stable -y
  - sudo apt-add-repository ppa:kalakris/cmake -y
  - sudo apt-get update -q
  - sudo apt-get install cmake libsfml-dev lcov
  - sudo pip install cpp-coveralls
script:
  - cmake --version
  - cmake -DCMAKE_BUILD_TYPE="Debug" .
  - make aquila_test
  - ctest
after_success:
  - coveralls --exclude examples --exclude lib --exclude tests
